//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RusRoadLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class RusRoadCommon
    {
        public int RusRoadCommon_Id { get; set; }
        public Nullable<System.DateTime> LastReport { get; set; }
    }
}
