//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RusRoadLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RusRoadsData : DbContext
    {
        public RusRoadsData()
            : base("name=RusRoadsData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarOwner> CarOwner { get; set; }
        public virtual DbSet<Highway> Highway { get; set; }
        public virtual DbSet<Passage> Passage { get; set; }
        public virtual DbSet<RusRoadCommon> RusRoadCommon { get; set; }
    }
}
